name: 'ClickUp chat action'
description: 'GitHub action wrapping the ClickUp Chat API'
author: 'Smplrspace'

branding:
  icon: 'hash'
  color: 'gray-dark'

env:
  CLICKUP_TOKEN:
    description: 'ClickUp token'
    required: true

inputs:
  workspace-id:
    description: 'ClickUp workspace ID'
    required: true
  channel-id:
    description: 'ClickUp chat channel ID'
    required: true
  message:
    description: 'Message to post to the chat channel'
    required: false
  status-update:
    description:
      'Set this to true to include an automated status update of the workflow in
      the message'
    required: false
  status:
    description:
      One of success, failure, or cancelled. Can be set using
      martialonline/workflow-status@v3.
    required: false

runs:
  using: node20
  main: dist/index.js
