name: Test

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: npm install && npm run bundle
      - name: Test custom message
        uses: ./
        with:
          workspace-id: ${{ secrets.workspace-id }}
          channel-id: ${{ secrets.channel-id }}
          message: |
            Can you read this? Then clickup-chat-action seems to work... 🎉
            And another test is coming right after for the automated status update
        env:
          CLICKUP_TOKEN: ${{ secrets.CLICKUP_TOKEN }}
      - name: Test status update
        uses: ./
        with:
          workspace-id: ${{ secrets.workspace-id }}
          channel-id: ${{ secrets.channel-id }}
          status-update: true
          status: success
        env:
          CLICKUP_TOKEN: ${{ secrets.CLICKUP_TOKEN }}
