name: RUN

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: npm install && npm run bundle

      - uses: ./
        with:
          CLICKUP_TOKEN: ${{ secrets.CLICKUP_TOKEN }}
          WORKSPACE_ID: ${{ secrets.WORKSPACE_ID }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          MESSAGE: Can read this? The clickup-chat-action seems to work... 🎉
